### ISSUE TITLE
Allow creating application tags with values larger than 30

### ISSUE THREAD

**Issue by dovreshef** [NLnetLabs/bcder#36]
I have a use case where the application tag for implicit sequence go up to 120.
Why the limitation of up to 30 (seen here https://docs.rs/bcder/0.4.0/src/bcder/tag.rs.html#189)?

**Comment by partim** [comment]
With this limitation, the tag can be stored in its encoded form in a single `u8`. This seemed a reasonable limitation at the time that saved a lot of conditional code. But this certainly can be changed.

**Comment by dovreshef** [comment]
Since the tags can be infinite in theory, how large do you thinks it should be? u32/u64?

Also, if I’d want to add support for it, would it be ok?

**Comment by partim** [comment]
I guess u32 would be enough? If you want to give the implementation a try, I’d be happy to accept a pull request.

**Comment by partim** [comment]
Thinking about this for a bit, the most elegant way might be to switch the type to by `pub struct Tal([u8; 4])` with the BER encoded tag at the beginning of the slice. Then it can be `AsRef<[u8]>` with the length of the slice determined according to the BER rules.

**Comment by dovreshef** [comment]
I've already wrote most of it this way.. but I'm not sure I understand what you mean by "with the length of the slice determined according to the BER rules".  I'm using the code mostly as is, just adding checks for multibyte case and handling it..

**Comment by partim** [comment]
Yeah, sorry, that’s pretty much what I mean.
